from survival_estimation.main import Lifespan
from survival_estimation.main import test_is_survival_curves

from survival_estimation.main import event_observed_color, event_censored_color
from survival_estimation.analysis import complete as complete_analysis
